### ISSUE TITLE
[Question] How do I use this?

### ISSUE THREAD

**Issue by rinsuki** [mumumusuc/pi-joystick#1]
I obtained `/dev/hidg0` using this library, but sending data there is not recognized by the Switch.
How do I use this?

my environment:
- Switch FW 8.0.1 (region: Japan, language: Japanese)
- Raspberry Pi Zero WH
- `uname -a` on my pi: `Linux switchpi 4.19.42+ #1219 Tue May 14 21:16:38 BST 2019 armv6l GNU/Linux`

my script:

```python3
import time
fp = open("/dev/hidg0", "wb")

s = bytes([
	0x30,
	0,
	8,
	0,
	0,
	0,
	0,
	0
])
print(s)
fp.write(s)
fp.flush()
time.sleep(0.1)
s = b'\0\0\x08\0\0\0\0\0'
print(s)
fp.write(s)
fp.flush()
fp.close()
```

Thanks!

**Comment by mumumusuc** [comment]
I uploaded the latest files,and using the "hori-s.h" as the default device.You can select between "Hori-s Gamepad" and "Nintendo Switch Pro" by modifying "joystick.h".
```
@ joystick.h

5 #include "hori-s.h"   // simulate hori device
5 #include "switch-pro.h" // simulate pro device
```
For "hori-s",sending `{0x30,0x00,0x00,0x00,0x00,0x00,0x00,0x00}` to connect to Switch.
For "switch-pro",following this [INSTRUCTION](https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/master/USB-HID-Notes.md) to connect to Switch.

**Comment by rinsuki** [comment]
really thanks!! it work!!!! 🙏
