### ISSUE TITLE
Can't write bytes into hidg0

### ISSUE THREAD

**Issue by WeiLai5432** [mumumusuc/pi-joystick#6]
I followed the project and installed the driver in Raspberry Pi 3B, but I can't write (or flush) bytes into hidg0. How to solve the problem? Thanks!
Here is the command line, and no response after echo.
```
pi@raspberrypi:~/pi-joystick ‹master*›$ ls -al /dev/hidg0   
crw-rw-rw- 1 root root 240, 0 Nov 12 12:35 /dev/hidg0
pi@raspberrypi:~/pi-joystick ‹master*›$ sudo echo -ne "\x04\x00\x00\x00\x00\x00\x00\x00" > /dev/hidg0


```

**Comment by mumumusuc** [comment]
Send {0x30,0x00,0x00,0x00,0x00,0x00,0x00,0x00} to connect to Switch firstly. I am NOT sure this driver can work with the newest system9.0.1, and I will test it later.

**Comment by WeiLai5432** [comment]
> Send {0x30,0x00,0x00,0x00,0x00,0x00,0x00,0x00} to connect to Switch firstly. I am NOT sure this driver can work with the newest system9.0.1, and I will test it later.

I can't write anything into the hidg0. Programm got stuck while trying flush bytes into the hidg0.

**Comment by mumumusuc** [comment]
I tested on NS(9.0.1),it still works!
Send (1) and (2) sequentially:
```
//1
echo -ne "\x00\x00\x00\x00\x00\x00\x00\x00" > /dev/hidg0
//2
echo -ne "\x30\x00\x00\x00\x00\x00\x00\x00" > /dev/hidg0    
```

**Comment by mumumusuc** [comment]
@WeiLai5432 Sadly，I don't think RPi3b can act as an OTG device.

**Comment by WeiLai5432** [comment]
> @WeiLai5432 Sadly，I don't think RPi3b can act as an OTG device.

@mumumusuc 
Yes, I checked the docs and found pi 3b can't act as an OTG device. Thank you.

I'm also following your project Bluetooth-Joycon but I didn't make it. Do you think it works with Pi 3B? I mailed you, looking for your reply.
