### ISSUE TITLE
dwc2_hsotg_ep_sethalt after insmod js_audio.ko

### ISSUE THREAD

**Issue by fusigi0930** [mumumusuc/pi-joystick#7]
Hi, I used rpi-zero-w and test it in my ubuntu, that works,
but it did not work in my switch (OS version: 9.1.0)
after I connect to switch, and I can see the log dwc2_hsotg_ep_sethalt is displayed.

and Switch no response while I send input report to /dev/hidg0

Do you have any idea about this?
Thanks,
ChuYuan

**Comment by mumumusuc** [comment]
Send (1) and (2) sequentially to connect to Switch(trigger R+L):
```
//1
echo -ne "\x00\x00\x00\x00\x00\x00\x00\x00" > /dev/hidg0
//2
echo -ne "\x30\x00\x00\x00\x00\x00\x00\x00" > /dev/hidg0
```

**Comment by fusigi0930** [comment]
that works, thanks
